---
apiVersion: v1
kind: Service
metadata:
  name: workout-log-api
  labels:
    app: workout-log-api
spec:
  type: ClusterIP
  selector:
    app: workout-log-api
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
